/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import customer.java;
import CustomerController.java;
import


/**
 *
 * @author LENOVO
 */
public class OrderTracking extends javax.swing.JFrame {

    /**
     * Creates new form OrderTracking
     */
    public OrderTracking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_TrackOrder = new javax.swing.JLabel();
        Label_EnterOrderID = new javax.swing.JLabel();
        TextField_OrderID = new javax.swing.JTextField();
        btn_TrackOrder = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();
        Panel_TrackOrder = new javax.swing.JPanel();
        Label_Status = new javax.swing.JLabel();
        Label_Vendor = new javax.swing.JLabel();
        TextField_Vendor = new javax.swing.JTextField();
        TextField_Status = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_TrackOrder.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Label_TrackOrder.setText("TRACK ORDER");

        Label_EnterOrderID.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Label_EnterOrderID.setText("Enter Order ID:");

        TextField_OrderID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextField_OrderID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TextField_OrderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_OrderIDActionPerformed(evt);
            }
        });

        btn_TrackOrder.setBackground(new java.awt.Color(0, 153, 255));
        btn_TrackOrder.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btn_TrackOrder.setText("Track Order");
        btn_TrackOrder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_TrackOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TrackOrderActionPerformed(evt);
            }
        });

        btn_Back.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btn_Back.setText("Back");
        btn_Back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        Panel_TrackOrder.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Label_Status.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_Status.setForeground(new java.awt.Color(0, 153, 255));
        Label_Status.setText("Status:");

        Label_Vendor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_Vendor.setForeground(new java.awt.Color(0, 153, 255));
        Label_Vendor.setText("Vendor: ");

        TextField_Vendor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_Vendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_VendorActionPerformed(evt);
            }
        });

        TextField_Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_StatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_TrackOrderLayout = new javax.swing.GroupLayout(Panel_TrackOrder);
        Panel_TrackOrder.setLayout(Panel_TrackOrderLayout);
        Panel_TrackOrderLayout.setHorizontalGroup(
            Panel_TrackOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TrackOrderLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(Panel_TrackOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Vendor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(Panel_TrackOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextField_Status, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(TextField_Vendor))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        Panel_TrackOrderLayout.setVerticalGroup(
            Panel_TrackOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TrackOrderLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(Panel_TrackOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Status)
                    .addComponent(TextField_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(Panel_TrackOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Vendor)
                    .addComponent(TextField_Vendor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_TrackOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_TrackOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_EnterOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextField_OrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_TrackOrder))
                    .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Label_TrackOrder)
                .addGap(27, 27, 27)
                .addComponent(Label_EnterOrderID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_OrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TrackOrder))
                .addGap(18, 18, 18)
                .addComponent(Panel_TrackOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_Back)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_OrderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_OrderIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_OrderIDActionPerformed

    private void btn_TrackOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TrackOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TrackOrderActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BackActionPerformed

    private void TextField_VendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_VendorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_VendorActionPerformed

    private void TextField_StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_StatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderTracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderTracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderTracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderTracking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderTracking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_EnterOrderID;
    private javax.swing.JLabel Label_Status;
    private javax.swing.JLabel Label_TrackOrder;
    private javax.swing.JLabel Label_Vendor;
    private javax.swing.JPanel Panel_TrackOrder;
    private javax.swing.JTextField TextField_OrderID;
    private javax.swing.JTextField TextField_Status;
    private javax.swing.JTextField TextField_Vendor;
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_TrackOrder;
    // End of variables declaration//GEN-END:variables
}
