/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.OrderController;
import model.Order;
import model.OrderStatus;
import util.FileHandler;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

public class RevenueDashboard extends javax.swing.JFrame {

    private JLabel lblTotalRevenue, lblOrdersCompleted;
    private JTextField txtTotalRevenue, txtOrdersCompleted;
    private JButton btnBack;

    public RevenueDashboard() {
        setTitle("Revenue Dashboard");
        setSize(500, 300);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(new GridLayout(4, 2, 10, 10));
        setLocationRelativeTo(null);

        lblTotalRevenue = new JLabel("Total Revenue (RM):");
        lblOrdersCompleted = new JLabel("Orders Completed:");
        txtTotalRevenue = new JTextField();
        txtOrdersCompleted = new JTextField();
        txtTotalRevenue.setEditable(false);
        txtOrdersCompleted.setEditable(false);
        btnBack = new JButton("Back");

        add(lblTotalRevenue);
        add(txtTotalRevenue);
        add(lblOrdersCompleted);
        add(txtOrdersCompleted);
        add(new JLabel()); // Empty space
        add(btnBack);

        // Load revenue data
        calculateRevenue();

        // Back button action
        btnBack.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose(); // Close the Revenue Dashboard
            }
        });
    }

    private void calculateRevenue() {
        List<Order> allOrders = FileHandler.getAllOrders();
        double totalRevenue = 0.0;
        int completedOrders = 0;

        for (Order order : allOrders) {
            if (order.getStatus().equals(OrderStatus.COMPLETED)) {
                totalRevenue += order.getTotalAmount();
                completedOrders++;
            }
        }

        txtTotalRevenue.setText(String.format("%.2f", totalRevenue));
        txtOrdersCompleted.setText(String.valueOf(completedOrders));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RevenueDashboard().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
