/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AdminController;
import model.Admin;
import javax.swing.*;
import java.awt.*;

public class AdminDashboard extends JFrame {

  
    private AdminController adminController;

    // Constructor
    public AdminDashboard(Admin admin, AdminController adminController1) {
        this.adminController = new AdminController(admin);

        setTitle("Admin Dashboard");
        setSize(800, 600);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());

        // ✅ Background Panel
        JPanel mainPanel = new JPanel(new BorderLayout());
        mainPanel.setBackground(new Color(235, 245, 251)); // Light Blue Background

        // ✅ Title Label
        JLabel titleLabel = new JLabel("Admin Dashboard", SwingConstants.CENTER);
        titleLabel.setFont(new Font("Arial", Font.BOLD, 28));
        titleLabel.setForeground(new Color(60, 63, 65)); // Dark Gray
        titleLabel.setOpaque(true);
        titleLabel.setBackground(new Color(200, 220, 240)); // Soft Blue
        titleLabel.setPreferredSize(new Dimension(800, 60));

        // ✅ Button Panel
        JPanel buttonPanel = new JPanel(new GridLayout(3, 2, 15, 15));
        buttonPanel.setBorder(BorderFactory.createEmptyBorder(20, 30, 20, 30));
        buttonPanel.setBackground(new Color(235, 245, 251));

        // ✅ Styled Buttons
        JButton manageUserBtn = createStyledButton("Manage User", new Color(255, 183, 183));
        JButton manageVendorsBtn = createStyledButton("View Vendors", new Color(255, 229, 183));
        JButton manageDeliveryRunnersBtn = createStyledButton("View Delivery Runners", new Color(183, 183, 255));
        JButton topUpButton = createStyledButton("Top-Up Credit",new Color(255, 183, 183));
        JButton generateReceiptBtn = createStyledButton("Generate Receipt", new Color(183,255,183));
        JButton logoutBtn = createStyledButton("Logout", new Color(255, 100, 100));

        // ✅ Logout Button Styling
        logoutBtn.setFont(new Font("Arial", Font.BOLD, 16));
        logoutBtn.setForeground(Color.WHITE);
        logoutBtn.setBorder(BorderFactory.createLineBorder(Color.RED, 2, true));

        // ✅ Add Buttons to Panel
        buttonPanel.add(manageUserBtn);
        buttonPanel.add(manageVendorsBtn);
        buttonPanel.add(manageDeliveryRunnersBtn);
        buttonPanel.add(topUpButton);
        buttonPanel.add(generateReceiptBtn);
        buttonPanel.add(logoutBtn);

        // ✅ Add Components to Frame
        mainPanel.add(titleLabel, BorderLayout.NORTH);
        mainPanel.add(buttonPanel, BorderLayout.CENTER);
        add(mainPanel);

        // ✅ Button Actions
        manageUserBtn.addActionListener(e -> adminController.editUser());
        manageVendorsBtn.addActionListener(e -> adminController.manageVendors());
        manageDeliveryRunnersBtn.addActionListener(e -> adminController.manageRunners());
        topUpButton.addActionListener(e -> adminController.topUpCustomerCredit());
        generateReceiptBtn.addActionListener(e -> adminController.generateAndSendReceipt());

        logoutBtn.addActionListener(e -> {
            dispose();
            SwingUtilities.invokeLater(() -> new LoginPage().setVisible(true));
        });

        setVisible(true);
    }

    // ✅ Styled Button Creation Method
    private JButton createStyledButton(String text, Color bgColor) {
        JButton button = new JButton(text);
        button.setFont(new Font("Arial", Font.BOLD, 14));
        button.setBackground(bgColor);
        button.setBorder(BorderFactory.createLineBorder(Color.GRAY, 2, true));
        button.setFocusPainted(false);
        button.setPreferredSize(new Dimension(300, 50)); // Bigger buttons
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        return button;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 828, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> {
            Admin admin = new Admin("admin123", "password", "Admin Name", "0123456789", "Admin Address");
            AdminController adminController = new AdminController(admin);
            new AdminDashboard(admin, adminController).setVisible(true);
        });


        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
