
package view;

import controller.ManagerController;
import model.Manager;
import javax.swing.*;
import java.awt.*;

public class ManagerDashboard extends JFrame {
    private ManagerController managerController;
    private Manager manager;

    public ManagerDashboard(Manager manager, ManagerController managerController) {
        this.manager = manager;
        this.managerController = managerController;

        setTitle("Manager Dashboard");
        setSize(600, 400);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        // Set a custom background color
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(3, 1, 10, 10)); // 10px spacing
        panel.setBackground(new Color(240, 240, 240)); // Light Gray Background
        panel.setBorder(BorderFactory.createEmptyBorder(30, 30, 30, 30)); // Add margins

        // Improved Button Styling
        JButton monitorPerformanceBtn = createStyledButton("📊 Monitor Performance", new Color(0, 153, 255)); // Blue
        JButton resolveComplaintsBtn = createStyledButton("⚠️ Resolve Complaints", new Color(255, 153, 0)); // Orange
        JButton logoutBtn = createStyledButton("🔴 Logout", new Color(255, 51, 51)); // Red

        // Button Actions
        monitorPerformanceBtn.addActionListener(e -> managerController.monitorPerformance());
        resolveComplaintsBtn.addActionListener(e -> resolveComplaints());
        logoutBtn.addActionListener(e -> {
            dispose(); // Close the Manager Dashboard
            new LoginPage().setVisible(true); // Open Login Page
        });

        panel.add(monitorPerformanceBtn);
        panel.add(resolveComplaintsBtn);
        panel.add(logoutBtn);

        add(panel);
        setVisible(true);
    }

    // ✅ Custom Method for Styled Buttons
    private JButton createStyledButton(String text, Color bgColor) {
        JButton button = new JButton(text);
        button.setFont(new Font("Arial", Font.BOLD, 16));
        button.setBackground(bgColor);
        button.setForeground(Color.WHITE);
        button.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 2, true));
        button.setFocusPainted(false);
        return button;
    }
    
    private void resolveComplaints(){
        managerController.showReviewsAndResolveComplaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      Manager manager = new Manager("M001", "password", "Manager Name", "0123456789", "Office Address");
        ManagerController managerController = new ManagerController(manager);
        new ManagerDashboard(manager, managerController);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
