package view;

import controller.UserController;
import model.User;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


public class SignUpFrame extends javax.swing.JFrame {

    private JTextField usernameField, nameField, mobileField;
    private JPasswordField passwordField;
    private JComboBox<String> roleComboBox;
    private JButton registerButton, backButton;

    public SignUpFrame() {
        setTitle("User Signup");
        setSize(700, 500);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(new GridLayout(6, 2));

        // Input Fields
        add(new JLabel("Username:"));
        usernameField = new JTextField();
        add(usernameField);

        add(new JLabel("Password:"));
        passwordField = new JPasswordField();
        add(passwordField);

        add(new JLabel("Full Name:"));
        nameField = new JTextField();
        add(nameField);

        add(new JLabel("Mobile Number:"));
        mobileField = new JTextField();
        add(mobileField);

        add(new JLabel("Role:"));
        String[] roles = {"CUSTOMER", "VENDOR", "MANAGER", "ADMIN", "DELIVERY RUNNER"};
        roleComboBox = new JComboBox<>(roles);
        add(roleComboBox);

        // Register Button
        registerButton = new JButton("Register");
        registerButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                registerUser();
            }
        });
        add(registerButton);

        JLabel titleLabel = new JLabel("User Signup", SwingConstants.CENTER); // Center text
        titleLabel.setFont(new Font("Arial", Font.BOLD, 24)); // Make text bigger
        JLabel nameLabel = new JLabel("Full Name:", SwingConstants.CENTER);

        registerButton = new JButton("Register");
        registerButton.setPreferredSize(new Dimension(80, 30)); // Smaller button size
        registerButton.setMargin(new Insets(2, 5, 2, 5)); // Less padding
        registerButton.setFont(new Font("Arial", Font.PLAIN, 10)); // Smaller text

        // Back Button
        backButton = new JButton("Back");
        backButton.addActionListener(e -> {
            new LoginPage().setVisible(true);
            dispose();
        });
        add(backButton);

        setLocationRelativeTo(null);
        setVisible(true);
        
        
    }

    private void registerUser() {
        String userID = usernameField.getText();
        String password = new String(passwordField.getPassword());
        String name = nameField.getText();
        String mobileNumber = mobileField.getText();
        String address = JOptionPane.showInputDialog("Enter Address:");
        String role = (String) roleComboBox.getSelectedItem();

        boolean success = UserController.registerUser(userID, password, name, mobileNumber, address, role);

        if (success) {
            JOptionPane.showMessageDialog(this, "Registration successful!");
            new LoginPage().setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Registration failed! Username may already exist.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
        



    /**
     * Creates new form SignUpFrame
     */
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
